version: "3.1"

services:
  dev-challenge1:
    image: postgres
    container_name: dev-challenge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
